/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BookRouteImport } from './routes/book'
import { Route as BuildRouteImport } from './routes/build'
import { Route as WorkCeilingAndEfficiencyRouteImport } from './routes/work.ceiling-and-efficiency'
import { Route as WorkPromotionAndExposureRouteImport } from './routes/work.promotion-and-exposure'
import { Route as WorkScaleAndConcentrationRouteImport } from './routes/work.scale-and-concentration'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkCeilingAndEfficiencyRoute =
  WorkCeilingAndEfficiencyRouteImport.update({
    id: '/work/ceiling-and-efficiency',
    path: '/work/ceiling-and-efficiency',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkPromotionAndExposureRoute =
  WorkPromotionAndExposureRouteImport.update({
    id: '/work/promotion-and-exposure',
    path: '/work/promotion-and-exposure',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkScaleAndConcentrationRoute =
  WorkScaleAndConcentrationRouteImport.update({
    id: '/work/scale-and-concentration',
    path: '/work/scale-and-concentration',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/book': typeof BookRoute
  '/build': typeof BuildRoute
  '/work/ceiling-and-efficiency': typeof WorkCeilingAndEfficiencyRoute
  '/work/promotion-and-exposure': typeof WorkPromotionAndExposureRoute
  '/work/scale-and-concentration': typeof WorkScaleAndConcentrationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/book': typeof BookRoute
  '/build': typeof BuildRoute
  '/work/ceiling-and-efficiency': typeof WorkCeilingAndEfficiencyRoute
  '/work/promotion-and-exposure': typeof WorkPromotionAndExposureRoute
  '/work/scale-and-concentration': typeof WorkScaleAndConcentrationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/book': typeof BookRoute
  '/build': typeof BuildRoute
  '/work/ceiling-and-efficiency': typeof WorkCeilingAndEfficiencyRoute
  '/work/promotion-and-exposure': typeof WorkPromotionAndExposureRoute
  '/work/scale-and-concentration': typeof WorkScaleAndConcentrationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/book'
    | '/build'
    | '/work/ceiling-and-efficiency'
    | '/work/promotion-and-exposure'
    | '/work/scale-and-concentration'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/book'
    | '/build'
    | '/work/ceiling-and-efficiency'
    | '/work/promotion-and-exposure'
    | '/work/scale-and-concentration'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/book'
    | '/build'
    | '/work/ceiling-and-efficiency'
    | '/work/promotion-and-exposure'
    | '/work/scale-and-concentration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  BookRoute: typeof BookRoute
  BuildRoute: typeof BuildRoute
  WorkCeilingAndEfficiencyRoute: typeof WorkCeilingAndEfficiencyRoute
  WorkPromotionAndExposureRoute: typeof WorkPromotionAndExposureRoute
  WorkScaleAndConcentrationRoute: typeof WorkScaleAndConcentrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/ceiling-and-efficiency': {
      id: '/work/ceiling-and-efficiency'
      path: '/work/ceiling-and-efficiency'
      fullPath: '/work/ceiling-and-efficiency'
      preLoaderRoute: typeof WorkCeilingAndEfficiencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/promotion-and-exposure': {
      id: '/work/promotion-and-exposure'
      path: '/work/promotion-and-exposure'
      fullPath: '/work/promotion-and-exposure'
      preLoaderRoute: typeof WorkPromotionAndExposureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/scale-and-concentration': {
      id: '/work/scale-and-concentration'
      path: '/work/scale-and-concentration'
      fullPath: '/work/scale-and-concentration'
      preLoaderRoute: typeof WorkScaleAndConcentrationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  BookRoute: BookRoute,
  BuildRoute: BuildRoute,
  WorkCeilingAndEfficiencyRoute: WorkCeilingAndEfficiencyRoute,
  WorkPromotionAndExposureRoute: WorkPromotionAndExposureRoute,
  WorkScaleAndConcentrationRoute: WorkScaleAndConcentrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
