/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as WorkLaunchAndHoldRouteImport } from './routes/work.launch-and-hold'
import { Route as WorkTrafficAndConversionRouteImport } from './routes/work.traffic-and-conversion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkLaunchAndHoldRoute = WorkLaunchAndHoldRouteImport.update({
  id: '/work/launch-and-hold',
  path: '/work/launch-and-hold',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkTrafficAndConversionRoute =
  WorkTrafficAndConversionRouteImport.update({
    id: '/work/traffic-and-conversion',
    path: '/work/traffic-and-conversion',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/work/launch-and-hold': typeof WorkLaunchAndHoldRoute
  '/work/traffic-and-conversion': typeof WorkTrafficAndConversionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/work/launch-and-hold': typeof WorkLaunchAndHoldRoute
  '/work/traffic-and-conversion': typeof WorkTrafficAndConversionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/work/launch-and-hold': typeof WorkLaunchAndHoldRoute
  '/work/traffic-and-conversion': typeof WorkTrafficAndConversionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/book' | '/work/launch-and-hold' | '/work/traffic-and-conversion'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/book' | '/work/launch-and-hold' | '/work/traffic-and-conversion'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/work/launch-and-hold'
    | '/work/traffic-and-conversion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  WorkLaunchAndHoldRoute: typeof WorkLaunchAndHoldRoute
  WorkTrafficAndConversionRoute: typeof WorkTrafficAndConversionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/launch-and-hold': {
      id: '/work/launch-and-hold'
      path: '/work/launch-and-hold'
      fullPath: '/work/launch-and-hold'
      preLoaderRoute: typeof WorkLaunchAndHoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/traffic-and-conversion': {
      id: '/work/traffic-and-conversion'
      path: '/work/traffic-and-conversion'
      fullPath: '/work/traffic-and-conversion'
      preLoaderRoute: typeof WorkTrafficAndConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  WorkLaunchAndHoldRoute: WorkLaunchAndHoldRoute,
  WorkTrafficAndConversionRoute: WorkTrafficAndConversionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
